import type { PresetBuild } from '@sim/presets/types';
import { Stats } from '@sim/proto/stats';
import type { IndividualSimHost } from '@sim/sim_host';
import { batch } from '@sim/state/batch';

export const applyBuild = (
	{ gear, itemSwap, rotation, rotationType, talents, epWeights, encounter, settings, reforgeSettings }: PresetBuild,
	simUI: IndividualSimHost<any>,
): void => {
	batch(() => {
		if (gear) simUI.player.setGear(simUI.sim.db.lookupEquipmentSpec(gear.gear));
		if (itemSwap) {
			simUI.player.itemSwapSettings.setItemSwapSettings(
				true,
				simUI.sim.db.lookupItemSwap(itemSwap.itemSwap),
				Stats.fromProto(itemSwap.itemSwap.prepullBonusStats),
			);
		} else {
			simUI.player.itemSwapSettings.setEnableItemSwap(false);
		}
		if (talents) {
			simUI.player.setTalentsString(talents.data.talentsString);
		}
		// A build may carry both. MoP's are generated by `makePresetBuildFromJSON`, which only
		// sets `rotationType` when the JSON's rotation is TypeAuto and therefore never records a
		// rotation alongside it — so MoP can treat the two as exclusive. TBC's builds are written
		// by hand and routinely carry `rotationType: TypeSimple` *and* a rotation, and taking the
		// first branch there drops the rotation on the floor: the Arms build would leave the Fury
		// spec rotation in place.
		if (rotationType && !rotation?.rotation.rotation) {
			simUI.player.modifyAplRotation(aplRotation => {
				aplRotation.type = rotationType;
			});
		} else if (rotation?.rotation.rotation) {
			// Type first, as vanilla did: it lets a preset that differs from the current rotation
			// only by type short-circuit setAplRotation's equality check.
			if (rotationType) {
				simUI.player.modifyAplRotation(aplRotation => {
					aplRotation.type = rotationType;
				});
			}
			simUI.player.setAplRotation(rotation.rotation.rotation);
		}
		if (epWeights) simUI.player.setEpWeights(epWeights.epWeights);
		if (settings) {
			if (settings.race) simUI.player.setRace(settings.race);
			if (settings.consumables) simUI.player.setConsumes(settings.consumables);
			if (settings.playerOptions?.profession1) simUI.player.setProfession1(settings.playerOptions.profession1);
			if (settings.playerOptions?.profession2) simUI.player.setProfession2(settings.playerOptions.profession2);
			if (typeof settings.playerOptions?.distanceFromTarget === 'number') simUI.player.setDistanceFromTarget(settings.playerOptions.distanceFromTarget);
			// Truthy, not `typeof === 'number'`. `makePresetBuildFromJSON` copies these two straight off
			// the parsed proto, where an absent field reads back as 0 — so a `typeof` guard applies a
			// zero the build never stated. The three tank specs' default build is an encounter-only
			// JSON carrying no player timings, and it was wiping their 100/250 ms reaction time.
			if (settings.playerOptions?.reactionTimeMs) simUI.player.setReactionTime(settings.playerOptions.reactionTimeMs);
			if (settings.playerOptions?.channelClipDelayMs) simUI.player.setChannelClipDelay(settings.playerOptions.channelClipDelayMs);
			if (typeof settings.playerOptions?.inFrontOfTarget === 'boolean') simUI.player.setInFrontOfTarget(settings.playerOptions.inFrontOfTarget);
			if (settings.playerOptions?.enableItemSwap !== undefined && settings.playerOptions?.itemSwap) {
				simUI.player.itemSwapSettings.setItemSwapSettings(
					settings.playerOptions.enableItemSwap,
					simUI.sim.db.lookupItemSwap(settings.playerOptions.itemSwap),
					Stats.fromProto(settings.playerOptions.itemSwap.prepullBonusStats),
				);
			}
			if (settings.specOptions) {
				simUI.player.setSpecOptions({
					...simUI.player.getSpecOptions(),
					...settings.specOptions,
				});
			}
			if (settings.raidBuffs) simUI.sim.raid.setBuffs(settings.raidBuffs);
			if (settings.partyBuffs) simUI.player.getParty()!.setBuffs(settings.partyBuffs);
			if (settings.buffs) simUI.player.setBuffs(settings.buffs);
			if (settings.debuffs) simUI.sim.raid.setDebuffs(settings.debuffs);
		}
		if (encounter) {
			if (encounter.encounter) simUI.sim.encounter.fromProto(encounter.encounter);
			if (encounter.healingModel) simUI.player.setHealingModel(encounter.healingModel);
			if (encounter.tanks) simUI.sim.raid.setTanks(encounter.tanks);
			if (encounter.targetDummies !== undefined) simUI.sim.raid.setTargetDummies(encounter.targetDummies);
		}
		if (reforgeSettings && simUI.reforger) {
			simUI.reforger.applyPresetSettings(reforgeSettings);
		}
	});
};
